import type { Card } from './types';

export type Rarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';

/**
 * Get the rarity tier for a card by ID.
 * Common: 1-10, Uncommon: 11-176, Rare: 177-226, Epic: 227-246, Legendary: 247-256
 */
export function getCardRarity(cardId: number): Rarity {
  if (cardId >= 247) return 'legendary';
  if (cardId >= 227) return 'epic';
  if (cardId >= 177) return 'rare';
  if (cardId >= 11) return 'uncommon';
  return 'common';
}

export const CARD_DATABASE: Card[] = [
  { id: 1, name: 'Mudwalker', ranks: { top: 1, right: 4, bottom: 1, left: 5 } },
  { id: 2, name: 'Blushy', ranks: { top: 5, right: 1, bottom: 1, left: 3 } },
  { id: 3, name: 'Snowdrop', ranks: { top: 1, right: 3, bottom: 3, left: 5 } },
  { id: 4, name: 'Sunny', ranks: { top: 6, right: 1, bottom: 1, left: 2 } },
  { id: 5, name: 'Inkwell', ranks: { top: 2, right: 3, bottom: 1, left: 5 } },
  { id: 6, name: 'Stripes', ranks: { top: 2, right: 1, bottom: 4, left: 4 } },
  { id: 7, name: 'Barkeeper', ranks: { top: 1, right: 5, bottom: 4, left: 1 } },
  { id: 8, name: 'Dotty', ranks: { top: 3, right: 1, bottom: 5, left: 2 } },
  { id: 9, name: 'Penny', ranks: { top: 2, right: 1, bottom: 6, left: 1 } },
  { id: 10, name: 'Peaches', ranks: { top: 4, right: 3, bottom: 2, left: 4 } },
  { id: 11, name: 'Freckles', ranks: { top: 2, right: 6, bottom: 1, left: 6 } },
  { id: 12, name: 'Camo', ranks: { top: 7, right: 1, bottom: 3, left: 1 } },
  { id: 13, name: 'Neon', ranks: { top: 6, right: 2, bottom: 2, left: 3 } },
  { id: 14, name: 'Glow Bug', ranks: { top: 5, right: 3, bottom: 3, left: 4 } },
  { id: 15, name: 'Limelight', ranks: { top: 6, right: 1, bottom: 4, left: 3 } },
  { id: 16, name: 'Marble', ranks: { top: 3, right: 4, bottom: 5, left: 3 } },
  { id: 17, name: 'Sapphire', ranks: { top: 5, right: 3, bottom: 2, left: 5 } },
  { id: 18, name: 'Jefferson', ranks: { top: 5, right: 1, bottom: 3, left: 5 } },
  { id: 19, name: 'Longfoot', ranks: { top: 5, right: 2, bottom: 5, left: 2 } },
  { id: 20, name: 'Featherfin', ranks: { top: 4, right: 2, bottom: 4, left: 5 } },
  { id: 21, name: 'Lilac', ranks: { top: 3, right: 7, bottom: 2, left: 5 } },
  { id: 22, name: 'Patches', ranks: { top: 5, right: 2, bottom: 5, left: 5 } },
  { id: 23, name: 'Faded', ranks: { top: 6, right: 6, bottom: 3, left: 3 } },
  { id: 24, name: 'Gold Dust', ranks: { top: 6, right: 3, bottom: 6, left: 3 } },
  { id: 25, name: 'Phantom', ranks: { top: 3, right: 5, bottom: 5, left: 5 } },
  { id: 26, name: 'Ash', ranks: { top: 7, right: 5, bottom: 1, left: 3 } },
  { id: 27, name: 'Cocoa', ranks: { top: 7, right: 1, bottom: 5, left: 3 } },
  { id: 28, name: 'Ringmaster', ranks: { top: 5, right: 3, bottom: 6, left: 3 } },
  { id: 29, name: 'Goldrush', ranks: { top: 5, right: 6, bottom: 2, left: 4 } },
  { id: 30, name: 'Swampling', ranks: { top: 4, right: 4, bottom: 7, left: 2 } },
  { id: 31, name: 'Glitter', ranks: { top: 3, right: 6, bottom: 4, left: 7 } },
  { id: 32, name: 'Starfield', ranks: { top: 7, right: 2, bottom: 3, left: 7 } },
  { id: 33, name: 'Specter', ranks: { top: 2, right: 3, bottom: 7, left: 7 } },
  { id: 34, name: 'Saffron', ranks: { top: 6, right: 5, bottom: 5, left: 5 } },
  { id: 35, name: 'Stardust', ranks: { top: 4, right: 7, bottom: 6, left: 2 } },
  { id: 36, name: 'Achoque', ranks: { top: 2, right: 3, bottom: 7, left: 8 } },
  { id: 37, name: 'Zacapu', ranks: { top: 1, right: 7, bottom: 6, left: 4 } },
  { id: 38, name: 'Laguna', ranks: { top: 7, right: 3, bottom: 1, left: 6 } },
  { id: 39, name: 'Streamwalker', ranks: { top: 7, right: 4, bottom: 4, left: 4 } },
  { id: 40, name: 'Digger', ranks: { top: 3, right: 7, bottom: 3, left: 6 } },
  { id: 41, name: 'Eclipse', ranks: { top: 6, right: 7, bottom: 3, left: 7 } },
  { id: 42, name: 'Kaleidoscope', ranks: { top: 6, right: 5, bottom: 8, left: 4 } },
  { id: 43, name: 'Twinned', ranks: { top: 6, right: 5, bottom: 6, left: 6 } },
  { id: 44, name: 'Sparkletail', ranks: { top: 3, right: 6, bottom: 7, left: 8 } },
  { id: 45, name: 'Riddler', ranks: { top: 7, right: 6, bottom: 5, left: 6 } },
  { id: 46, name: 'Rosita', ranks: { top: 3, right: 10, bottom: 2, left: 1 } },
  { id: 47, name: 'Brooklet', ranks: { top: 6, right: 2, bottom: 6, left: 7 } },
  { id: 48, name: 'Whisper', ranks: { top: 5, right: 5, bottom: 7, left: 6 } },
  { id: 49, name: 'Misty', ranks: { top: 7, right: 7, bottom: 4, left: 2 } },
  { id: 50, name: 'Lerma', ranks: { top: 7, right: 2, bottom: 7, left: 4 } },
  { id: 51, name: 'Puddle', ranks: { top: 4, right: 2, bottom: 6, left: 3 } },
  { id: 52, name: 'Trickle', ranks: { top: 2, right: 5, bottom: 3, left: 6 } },
  { id: 53, name: 'Dewdrop', ranks: { top: 5, right: 1, bottom: 4, left: 5 } },
  { id: 54, name: 'Sprout', ranks: { top: 2, right: 4, bottom: 1, left: 6 } },
  { id: 55, name: 'Nibbles', ranks: { top: 3, right: 2, bottom: 4, left: 5 } },
  { id: 56, name: 'Pebble', ranks: { top: 4, right: 2, bottom: 5, left: 2 } },
  { id: 57, name: 'Clover', ranks: { top: 2, right: 1, bottom: 5, left: 5 } },
  { id: 58, name: 'Dapple', ranks: { top: 6, right: 1, bottom: 6, left: 3 } },
  { id: 59, name: 'Flicker', ranks: { top: 5, right: 1, bottom: 6, left: 3 } },
  { id: 60, name: 'Rustle', ranks: { top: 1, right: 5, bottom: 2, left: 6 } },
  { id: 61, name: 'Wisp', ranks: { top: 4, right: 5, bottom: 2, left: 2 } },
  { id: 62, name: 'Bramble', ranks: { top: 4, right: 3, bottom: 6, left: 3 } },
  { id: 63, name: 'Thistle', ranks: { top: 4, right: 1, bottom: 6, left: 4 } },
  { id: 64, name: 'Burrow', ranks: { top: 4, right: 4, bottom: 2, left: 5 } },
  { id: 65, name: 'Cricket', ranks: { top: 5, right: 2, bottom: 6, left: 2 } },
  { id: 66, name: 'Minnow', ranks: { top: 2, right: 4, bottom: 5, left: 1 } },
  { id: 67, name: 'Pinecone', ranks: { top: 2, right: 4, bottom: 1, left: 5 } },
  { id: 68, name: 'Acorn', ranks: { top: 3, right: 3, bottom: 1, left: 6 } },
  { id: 69, name: 'Mushroom', ranks: { top: 3, right: 5, bottom: 2, left: 3 } },
  { id: 70, name: 'Fiddlehead', ranks: { top: 4, right: 3, bottom: 3, left: 4 } },
  { id: 71, name: 'Tadpole', ranks: { top: 5, right: 6, bottom: 2, left: 2 } },
  { id: 72, name: 'Drizzle', ranks: { top: 2, right: 3, bottom: 5, left: 4 } },
  { id: 73, name: 'Duskweed', ranks: { top: 2, right: 6, bottom: 3, left: 1 } },
  { id: 74, name: 'Cattail', ranks: { top: 2, right: 6, bottom: 3, left: 5 } },
  { id: 75, name: 'Bulrush', ranks: { top: 1, right: 2, bottom: 6, left: 6 } },
  { id: 76, name: 'Lichen', ranks: { top: 1, right: 4, bottom: 6, left: 5 } },
  { id: 77, name: 'Toadskin', ranks: { top: 2, right: 3, bottom: 4, left: 6 } },
  { id: 78, name: 'Barnacle', ranks: { top: 4, right: 1, bottom: 5, left: 2 } },
  { id: 79, name: 'Kelp', ranks: { top: 2, right: 3, bottom: 6, left: 1 } },
  { id: 80, name: 'Driftwood', ranks: { top: 3, right: 5, bottom: 2, left: 5 } },
  { id: 81, name: 'Ripple', ranks: { top: 6, right: 2, bottom: 2, left: 4 } },
  { id: 82, name: 'Current', ranks: { top: 1, right: 6, bottom: 5, left: 3 } },
  { id: 83, name: 'Eddy', ranks: { top: 6, right: 3, bottom: 1, left: 4 } },
  { id: 84, name: 'Brook', ranks: { top: 1, right: 6, bottom: 2, left: 5 } },
  { id: 85, name: 'Mossheart', ranks: { top: 5, right: 1, bottom: 6, left: 2 } },
  { id: 86, name: 'Reedling', ranks: { top: 3, right: 4, bottom: 6, left: 1 } },
  { id: 87, name: 'Fernback', ranks: { top: 6, right: 5, bottom: 1, left: 1 } },
  { id: 88, name: 'Cobble', ranks: { top: 5, right: 3, bottom: 2, left: 4 } },
  { id: 89, name: 'Shingle', ranks: { top: 6, right: 1, bottom: 1, left: 6 } },
  { id: 90, name: 'Dampfoot', ranks: { top: 6, right: 4, bottom: 1, left: 2 } },
  { id: 91, name: 'Mudskipper', ranks: { top: 3, right: 6, bottom: 1, left: 5 } },
  { id: 92, name: 'Puddlejump', ranks: { top: 2, right: 5, bottom: 3, left: 5 } },
  { id: 93, name: 'Bogbean', ranks: { top: 4, right: 1, bottom: 3, left: 6 } },
  { id: 94, name: 'Waterlily', ranks: { top: 1, right: 4, bottom: 6, left: 4 } },
  { id: 95, name: 'Pondweed', ranks: { top: 6, right: 5, bottom: 4, left: 1 } },
  { id: 96, name: 'Duckweed', ranks: { top: 1, right: 2, bottom: 6, left: 6 } },
  { id: 97, name: 'Silverfin', ranks: { top: 3, right: 2, bottom: 3, left: 5 } },
  { id: 98, name: 'Quicksand', ranks: { top: 2, right: 6, bottom: 1, left: 6 } },
  { id: 99, name: 'Rainfall', ranks: { top: 4, right: 6, bottom: 4, left: 2 } },
  { id: 100, name: 'Foghorn', ranks: { top: 3, right: 5, bottom: 3, left: 2 } },
  { id: 101, name: 'Mistletoe', ranks: { top: 6, right: 3, bottom: 2, left: 5 } },
  { id: 102, name: 'Juniper', ranks: { top: 5, right: 5, bottom: 2, left: 1 } },
  { id: 103, name: 'Hazelnut', ranks: { top: 1, right: 4, bottom: 5, left: 6 } },
  { id: 104, name: 'Walnut', ranks: { top: 1, right: 5, bottom: 5, left: 2 } },
  { id: 105, name: 'Chestnut', ranks: { top: 6, right: 5, bottom: 1, left: 2 } },
  { id: 106, name: 'Birchbark', ranks: { top: 2, right: 3, bottom: 5, left: 4 } },
  { id: 107, name: 'Pinewood', ranks: { top: 2, right: 2, bottom: 4, left: 5 } },
  { id: 108, name: 'Willowbend', ranks: { top: 6, right: 3, bottom: 3, left: 4 } },
  { id: 109, name: 'Elmshade', ranks: { top: 2, right: 5, bottom: 4, left: 5 } },
  { id: 110, name: 'Ashleaf', ranks: { top: 3, right: 4, bottom: 4, left: 3 } },
  { id: 111, name: 'Oakmoss', ranks: { top: 3, right: 3, bottom: 1, left: 5 } },
  { id: 112, name: 'Cedarbloom', ranks: { top: 3, right: 4, bottom: 2, left: 3 } },
  { id: 113, name: 'Magnolia', ranks: { top: 5, right: 2, bottom: 1, left: 6 } },
  { id: 114, name: 'Dahlia', ranks: { top: 5, right: 3, bottom: 4, left: 2 } },
  { id: 115, name: 'Poppy', ranks: { top: 4, right: 6, bottom: 1, left: 5 } },
  { id: 116, name: 'Marigold', ranks: { top: 1, right: 6, bottom: 2, left: 5 } },
  { id: 117, name: 'Buttercup', ranks: { top: 1, right: 6, bottom: 2, left: 6 } },
  { id: 118, name: 'Bluebell', ranks: { top: 3, right: 2, bottom: 6, left: 4 } },
  { id: 119, name: 'Foxglove', ranks: { top: 4, right: 6, bottom: 2, left: 3 } },
  { id: 120, name: 'Harebell', ranks: { top: 5, right: 3, bottom: 2, left: 5 } },
  { id: 121, name: 'Primrose', ranks: { top: 5, right: 4, bottom: 3, left: 3 } },
  { id: 122, name: 'Snapdragon', ranks: { top: 2, right: 4, bottom: 5, left: 5 } },
  { id: 123, name: 'Aster', ranks: { top: 2, right: 6, bottom: 1, left: 6 } },
  { id: 124, name: 'Zinnia', ranks: { top: 2, right: 5, bottom: 1, left: 4 } },
  { id: 125, name: 'Viola', ranks: { top: 4, right: 1, bottom: 5, left: 5 } },
  { id: 126, name: 'Petunia', ranks: { top: 5, right: 4, bottom: 2, left: 3 } },
  { id: 127, name: 'Hyacinth', ranks: { top: 6, right: 4, bottom: 3, left: 3 } },
  { id: 128, name: 'Crocus', ranks: { top: 6, right: 3, bottom: 3, left: 3 } },
  { id: 129, name: 'Tulip', ranks: { top: 4, right: 5, bottom: 6, left: 1 } },
  { id: 130, name: 'Iris', ranks: { top: 5, right: 2, bottom: 6, left: 3 } },
  { id: 131, name: 'Orchid', ranks: { top: 5, right: 4, bottom: 5, left: 2 } },
  { id: 132, name: 'Pansy', ranks: { top: 4, right: 4, bottom: 2, left: 6 } },
  { id: 133, name: 'Jasmine', ranks: { top: 2, right: 4, bottom: 4, left: 4 } },
  { id: 134, name: 'Lavender', ranks: { top: 1, right: 6, bottom: 2, left: 4 } },
  { id: 135, name: 'Rosemary', ranks: { top: 3, right: 1, bottom: 6, left: 5 } },
  { id: 136, name: 'Thyme', ranks: { top: 6, right: 1, bottom: 5, left: 3 } },
  { id: 137, name: 'Basil', ranks: { top: 3, right: 2, bottom: 5, left: 6 } },
  { id: 138, name: 'Sage', ranks: { top: 3, right: 6, bottom: 3, left: 1 } },
  { id: 139, name: 'Parsley', ranks: { top: 4, right: 4, bottom: 1, left: 5 } },
  { id: 140, name: 'Fennel', ranks: { top: 1, right: 6, bottom: 6, left: 3 } },
  { id: 141, name: 'Dill', ranks: { top: 3, right: 3, bottom: 4, left: 3 } },
  { id: 142, name: 'Chive', ranks: { top: 2, right: 4, bottom: 3, left: 5 } },
  { id: 143, name: 'Oregano', ranks: { top: 1, right: 6, bottom: 4, left: 1 } },
  { id: 144, name: 'Tarragon', ranks: { top: 2, right: 6, bottom: 1, left: 4 } },
  { id: 145, name: 'Anise', ranks: { top: 6, right: 4, bottom: 2, left: 1 } },
  { id: 146, name: 'Cardamom', ranks: { top: 4, right: 3, bottom: 6, left: 1 } },
  { id: 147, name: 'Cinnamon', ranks: { top: 5, right: 5, bottom: 1, left: 3 } },
  { id: 148, name: 'Ginger', ranks: { top: 1, right: 4, bottom: 1, left: 6 } },
  { id: 149, name: 'Nutmeg', ranks: { top: 6, right: 3, bottom: 6, left: 1 } },
  { id: 150, name: 'Saffie', ranks: { top: 4, right: 1, bottom: 1, left: 6 } },
  { id: 151, name: 'Tumeric', ranks: { top: 1, right: 4, bottom: 5, left: 5 } },
  { id: 152, name: 'Cayenne', ranks: { top: 4, right: 5, bottom: 1, left: 3 } },
  { id: 153, name: 'Paprika', ranks: { top: 1, right: 1, bottom: 5, left: 6 } },
  { id: 154, name: 'Cumin', ranks: { top: 6, right: 5, bottom: 3, left: 1 } },
  { id: 155, name: 'Coriander', ranks: { top: 4, right: 4, bottom: 1, left: 6 } },
  { id: 156, name: 'Clove', ranks: { top: 6, right: 1, bottom: 3, left: 3 } },
  { id: 157, name: 'Allspice', ranks: { top: 5, right: 3, bottom: 3, left: 3 } },
  { id: 158, name: 'Pimento', ranks: { top: 1, right: 4, bottom: 4, left: 6 } },
  { id: 159, name: 'Sumac', ranks: { top: 3, right: 6, bottom: 2, left: 4 } },
  { id: 160, name: 'Sesame', ranks: { top: 2, right: 3, bottom: 1, left: 6 } },
  { id: 161, name: 'Starflower', ranks: { top: 1, right: 6, bottom: 1, left: 5 } },
  { id: 162, name: 'Moonpetal', ranks: { top: 2, right: 6, bottom: 2, left: 3 } },
  { id: 163, name: 'Sundew', ranks: { top: 1, right: 5, bottom: 4, left: 5 } },
  { id: 164, name: 'Nightbloom', ranks: { top: 1, right: 5, bottom: 6, left: 1 } },
  { id: 165, name: 'Dawnbreeze', ranks: { top: 5, right: 2, bottom: 5, left: 4 } },
  { id: 166, name: 'Duskbell', ranks: { top: 5, right: 4, bottom: 5, left: 1 } },
  { id: 167, name: 'Twilight', ranks: { top: 2, right: 4, bottom: 6, left: 1 } },
  { id: 168, name: 'Gloaming', ranks: { top: 2, right: 3, bottom: 2, left: 5 } },
  { id: 169, name: 'Haze', ranks: { top: 3, right: 5, bottom: 2, left: 6 } },
  { id: 170, name: 'Vapor', ranks: { top: 5, right: 2, bottom: 3, left: 6 } },
  { id: 171, name: 'Cloudburst', ranks: { top: 4, right: 1, bottom: 6, left: 4 } },
  { id: 172, name: 'Sleet', ranks: { top: 6, right: 4, bottom: 1, left: 5 } },
  { id: 173, name: 'Drizzletail', ranks: { top: 5, right: 3, bottom: 5, left: 3 } },
  { id: 174, name: 'Steamvent', ranks: { top: 2, right: 2, bottom: 4, left: 6 } },
  { id: 175, name: 'Fogcrawler', ranks: { top: 6, right: 2, bottom: 5, left: 2 } },
  { id: 176, name: 'Mistwalker', ranks: { top: 3, right: 5, bottom: 3, left: 2 } },
  { id: 177, name: 'Abyssal', ranks: { top: 5, right: 6, bottom: 5, left: 3 } },
  { id: 178, name: 'Tidecaller', ranks: { top: 8, right: 3, bottom: 5, left: 2 } },
  { id: 179, name: 'Moonshadow', ranks: { top: 5, right: 5, bottom: 7, left: 2 } },
  { id: 180, name: 'Stormwarden', ranks: { top: 8, right: 3, bottom: 3, left: 8 } },
  { id: 181, name: 'Deeproot', ranks: { top: 4, right: 7, bottom: 4, left: 3 } },
  { id: 182, name: 'Crystalvein', ranks: { top: 8, right: 5, bottom: 6, left: 2 } },
  { id: 183, name: 'Nightfall', ranks: { top: 2, right: 5, bottom: 6, left: 5 } },
  { id: 184, name: 'Thornweaver', ranks: { top: 3, right: 4, bottom: 8, left: 7 } },
  { id: 185, name: 'Emberclaw', ranks: { top: 7, right: 7, bottom: 5, left: 2 } },
  { id: 186, name: 'Frostfang', ranks: { top: 2, right: 7, bottom: 5, left: 5 } },
  { id: 187, name: 'Ironbark', ranks: { top: 2, right: 3, bottom: 6, left: 7 } },
  { id: 188, name: 'Silverscale', ranks: { top: 8, right: 4, bottom: 3, left: 4 } },
  { id: 189, name: 'Goldmane', ranks: { top: 7, right: 6, bottom: 2, left: 7 } },
  { id: 190, name: 'Bronzewing', ranks: { top: 8, right: 3, bottom: 6, left: 2 } },
  { id: 191, name: 'Coppertail', ranks: { top: 3, right: 7, bottom: 8, left: 4 } },
  { id: 192, name: 'Steelheart', ranks: { top: 5, right: 4, bottom: 6, left: 2 } },
  { id: 193, name: 'Cobaltfin', ranks: { top: 3, right: 2, bottom: 5, left: 7 } },
  { id: 194, name: 'Chromatic', ranks: { top: 7, right: 5, bottom: 3, left: 3 } },
  { id: 195, name: 'Prismatic', ranks: { top: 8, right: 5, bottom: 2, left: 5 } },
  { id: 196, name: 'Opalescent', ranks: { top: 7, right: 4, bottom: 8, left: 3 } },
  { id: 197, name: 'Pearlshine', ranks: { top: 5, right: 7, bottom: 5, left: 2 } },
  { id: 198, name: 'Amethyst', ranks: { top: 2, right: 8, bottom: 2, left: 7 } },
  { id: 199, name: 'Emeraldine', ranks: { top: 6, right: 2, bottom: 7, left: 3 } },
  { id: 200, name: 'Rubythorn', ranks: { top: 6, right: 4, bottom: 5, left: 3 } },
  { id: 201, name: 'Topazglow', ranks: { top: 4, right: 3, bottom: 4, left: 7 } },
  { id: 202, name: 'Garnetflare', ranks: { top: 7, right: 2, bottom: 6, left: 5 } },
  { id: 203, name: 'Obsidian', ranks: { top: 4, right: 4, bottom: 5, left: 7 } },
  { id: 204, name: 'Onyx', ranks: { top: 6, right: 8, bottom: 2, left: 2 } },
  { id: 205, name: 'Turquoise', ranks: { top: 5, right: 2, bottom: 3, left: 8 } },
  { id: 206, name: 'Malachite', ranks: { top: 4, right: 4, bottom: 8, left: 6 } },
  { id: 207, name: 'Lazuli', ranks: { top: 8, right: 8, bottom: 3, left: 3 } },
  { id: 208, name: 'Aquamarine', ranks: { top: 8, right: 6, bottom: 2, left: 4 } },
  { id: 209, name: 'Beryl', ranks: { top: 3, right: 7, bottom: 4, left: 7 } },
  { id: 210, name: 'Zircon', ranks: { top: 8, right: 3, bottom: 6, left: 3 } },
  { id: 211, name: 'Agate', ranks: { top: 2, right: 2, bottom: 6, left: 7 } },
  { id: 212, name: 'Jasper', ranks: { top: 2, right: 7, bottom: 2, left: 6 } },
  { id: 213, name: 'Carnelian', ranks: { top: 7, right: 3, bottom: 8, left: 2 } },
  { id: 214, name: 'Moonstone', ranks: { top: 4, right: 7, bottom: 5, left: 3 } },
  { id: 215, name: 'Sunstone', ranks: { top: 2, right: 2, bottom: 7, left: 8 } },
  { id: 216, name: 'Bloodstone', ranks: { top: 4, right: 7, bottom: 6, left: 2 } },
  { id: 217, name: 'Thunderjaw', ranks: { top: 7, right: 3, bottom: 6, left: 3 } },
  { id: 218, name: 'Stormscale', ranks: { top: 5, right: 3, bottom: 6, left: 8 } },
  { id: 219, name: 'Windwalker', ranks: { top: 2, right: 5, bottom: 8, left: 7 } },
  { id: 220, name: 'Firebrand', ranks: { top: 7, right: 3, bottom: 2, left: 5 } },
  { id: 221, name: 'Iceveil', ranks: { top: 7, right: 4, bottom: 4, left: 3 } },
  { id: 222, name: 'Voidtouched', ranks: { top: 8, right: 3, bottom: 2, left: 6 } },
  { id: 223, name: 'Netherbloom', ranks: { top: 8, right: 2, bottom: 5, left: 6 } },
  { id: 224, name: 'Spiritfang', ranks: { top: 6, right: 5, bottom: 4, left: 5 } },
  { id: 225, name: 'Soulreaver', ranks: { top: 6, right: 8, bottom: 6, left: 2 } },
  { id: 226, name: 'Doomhowl', ranks: { top: 3, right: 8, bottom: 4, left: 5 } },
  { id: 227, name: 'Oblivion', ranks: { top: 6, right: 3, bottom: 9, left: 4 } },
  { id: 228, name: 'Cataclysm', ranks: { top: 4, right: 9, bottom: 9, left: 4 } },
  { id: 229, name: 'Apocalypse', ranks: { top: 8, right: 9, bottom: 3, left: 3 } },
  { id: 230, name: 'Ragnarok', ranks: { top: 7, right: 3, bottom: 4, left: 9 } },
  { id: 231, name: 'Armageddon', ranks: { top: 6, right: 4, bottom: 9, left: 4 } },
  { id: 232, name: 'Leviathan', ranks: { top: 7, right: 9, bottom: 7, left: 3 } },
  { id: 233, name: 'Behemoth', ranks: { top: 4, right: 3, bottom: 6, left: 9 } },
  { id: 234, name: 'Colossus', ranks: { top: 6, right: 8, bottom: 4, left: 4 } },
  { id: 235, name: 'Juggernaut', ranks: { top: 7, right: 7, bottom: 4, left: 7 } },
  { id: 236, name: 'Titan', ranks: { top: 9, right: 3, bottom: 6, left: 4 } },
  { id: 237, name: 'Seraphim', ranks: { top: 8, right: 8, bottom: 3, left: 3 } },
  { id: 238, name: 'Nephilim', ranks: { top: 9, right: 9, bottom: 4, left: 5 } },
  { id: 239, name: 'Archon', ranks: { top: 9, right: 3, bottom: 8, left: 4 } },
  { id: 240, name: 'Sovereign', ranks: { top: 3, right: 6, bottom: 8, left: 9 } },
  { id: 241, name: 'Imperator', ranks: { top: 9, right: 3, bottom: 8, left: 3 } },
  { id: 242, name: 'Nexus', ranks: { top: 8, right: 3, bottom: 8, left: 8 } },
  { id: 243, name: 'Singularity', ranks: { top: 4, right: 9, bottom: 4, left: 7 } },
  { id: 244, name: 'Infinity', ranks: { top: 8, right: 9, bottom: 6, left: 3 } },
  { id: 245, name: 'Eternity', ranks: { top: 4, right: 4, bottom: 7, left: 8 } },
  { id: 246, name: 'Genesis', ranks: { top: 6, right: 7, bottom: 8, left: 3 } },
  { id: 247, name: 'Eclipse', ranks: { top: 6, right: 7, bottom: 3, left: 7 } },
  { id: 248, name: 'Kaleidoscope', ranks: { top: 6, right: 5, bottom: 8, left: 4 } },
  { id: 249, name: 'Twinned', ranks: { top: 6, right: 5, bottom: 6, left: 6 } },
  { id: 250, name: 'Sparkletail', ranks: { top: 3, right: 6, bottom: 7, left: 8 } },
  { id: 251, name: 'Riddler', ranks: { top: 7, right: 6, bottom: 5, left: 6 } },
  { id: 252, name: 'Rosita', ranks: { top: 3, right: 10, bottom: 2, left: 1 } },
  { id: 253, name: 'Brooklet', ranks: { top: 6, right: 2, bottom: 6, left: 7 } },
  { id: 254, name: 'Whisper', ranks: { top: 5, right: 5, bottom: 7, left: 6 } },
  { id: 255, name: 'Misty', ranks: { top: 7, right: 7, bottom: 4, left: 2 } },
  { id: 256, name: 'Lerma', ranks: { top: 7, right: 2, bottom: 7, left: 4 } },
];

export function getCardById(id: number): Card | undefined {
  return CARD_DATABASE.find(c => c.id === id);
}

export function getRandomHand(count = 5): Card[] {
  const shuffled = [...CARD_DATABASE].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count).map(c => ({ ...c }));
}

export function getRandomHandIds(availableIds: number[], count = 5): number[] {
  if (availableIds.length <= count) return [...availableIds];
  const shuffled = [...availableIds].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}

export function formatRank(rank: number): string {
  return rank === 10 ? 'A' : String(rank);
}
